name: Deploy to GitHub Pages

on:
  push

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          repository: dreamcatcher-tech/dreamcatcher-stack
          # Pull only the latest released version
          ref: refs/tags/v1.0.107
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install
        run: yarn install --focus --frozen-lockfile
        working-directory: ./pkg/dreamcatcher

      - name: Build
        run: yarn build
        working-directory: ./pkg/dreamcatcher
        env: 
          NODE_OPTIONS: --max-old-space-size=8192
          VITE_INFURA_API_KEY: ${{ secrets.VITE_INFURA_API_KEY }}
          VITE_INFURA_IPFS_KEY: ${{ secrets.VITE_INFURA_IPFS_KEY }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pkg/dreamcatcher/dist
          cname: app.dreamcatcher.land